#!/bin/sh

#DB=1
#INSTALL=1

CMDS=$1

PREFIX=/usr/local

FLAGS="--prefix ${PREFIX}"

if test "x${DB}" = x1 ; then
FLAGS="$FLAGS --disable-shared --enable-static"
CFLAGS="-g -O0"
else
FLAGS="$FLAGS --enable-shared"
fi

CFLAGS="${CFLAGS} -Wno-attributes"

export CFLAGS
DISTCHECK_CONFIGURE_FLAGS="$FLAGS"
export DISTCHECK_CONFIGURE_FLAGS

if autoreconf -i --force ; then ok=1; else exit ; fi

if test -z "$FAST" ; then
  if test -f Makefile ; then ${MAKE} distclean >/dev/null 2>&1 ; fi
fi
sh $X ./configure ${FLAGS}
if test "x$CMDS" != x ; then
make $CMDS
fi
exit 0
